### ISSUE TITLE
Amplitude initialize question

### ISSUE THREAD

**Issue by Arrefelt** [amplitude/Amplitude-Android#100]
Hello, this is just a question and not a issue.

Regarding initialization of the context, can this be put in the application object instead of in the MainActivity/every starting activity of the app?

So instead of this:

`Amplitude.getInstance().initialize(this,"YOUR_API_KEY_HERE").enableForegroundTracking(getApplication());
`

It would look more like this:

`Amplitude.getInstance().initialize(this,"YOUR_API_KEY_HERE").enableForegroundTracking(this);`

I've seen many libraries using this approach for context registering.

**Comment by djih** [comment]
Should be fine. You just have to make sure you're initializing with the API key before you use any of the other functions, otherwise it will print out a warning message. A lot of people initialize in the starting activity because they might want to log an event as soon as the app opens. Just test it and see if you are logging events as expected
