### ISSUE TITLE
Initialize SDK in Application class rather than Activity?

### ISSUE THREAD

**Issue by daisy1754** [amplitude/Amplitude-Android#26]
Hi,

In the README, you recommend initialize SDK in Activity#onCreate()
> In the onCreate() of your main activity, initialize the SDK:

Is there any reason we should avoid do this during Application#onCreate?
If users launch our app via push notification, they may not open our "main" activity. Is there any reason you prefer Activity#onCreate over Application#onCreate?

**Comment by kevintanhongann** [comment]
I'm also thinking the same thing. As of now, does the initialization work in the application class?

**Comment by allanca** [comment]
Typically, Android has suggested not using an Application class (https://developer.android.com/reference/android/app/Application.html). Though if you're using one, it will work to initialize the SDK in Application.onCreate instead of in your main activity.

Or, you can call initialize in the onCreate of each Activity you log events from. Calling initialize multiple times is not a problem.
