### ISSUE TITLE
Add consumer rule

### ISSUE THREAD

**Issue by zmunm** [amplitude/Amplitude-Android#288]
## Summary
Add consumer rule

## Motivations
Amplitude-Android is importing AdvertisingIdClient and GooglePlayServicesUtil as `forName` in [DeviceInfo](https://github.com/amplitude/Amplitude-Android/blob/1ab2ecd793afdbade883164aa711a2e175e047c5/src/main/java/com/amplitude/api/DeviceInfo.java)

If this is acceptable then I can work on it.

**Comment by dantetam** [comment]
Hello @zmunm ,

You mean add a new Proguard rule? The reflection is very intentional in the structure of our SDK, and we expect users that want IDFA to [add the Proguard rules themselves](https://developers.amplitude.com/docs/android#3-add-proguard-exception). Otherwise, the app will throw a soft error that the API is missing. This is for flexibility in whether or not a user would want to include the relevant Google Android libraries inside their apps. If there's any context I'm missing, please provide it to our team here.

Dante

**Comment by zmunm** [comment]
Hello @dantetam 

I couldn't check that section. Thank you.
