### ISSUE TITLE
Versioning: v2 or v3?

### ISSUE THREAD

**Issue by ubuntudroid** [amplitude/Amplitude-Android#312]
## Summary

[This commit](https://github.com/amplitude/Amplitude-Android/commit/770f6b8818776b5dd7379f9a1f5a213c784859ca) changes the major version from v2 to v3. Maven also supplies the new v3 version. However, there are only v2 release tags on github.

Was this change just a mistake? Should we use the 3.x version supplied by maven?

**Comment by haoliu-amp** [comment]
@ubuntudroid Really sorry for the confusion. Please continue to use v2. We released the v3 by mistake. We're in the process of contacting sonatype to pull v3 down.

**Comment by ubuntudroid** [comment]
Can you post here once v3 has been removed? 🙏

**Comment by haoliu-amp** [comment]
Yep, we will definitely do that.

**Comment by ubuntudroid** [comment]
@haoliu-amp what's the status here?

**Comment by yuhao900914** [comment]
@ubuntudroid  Sorry about the confusion. Sonaytype policy prohibits the removal or modification of artifacts after release. So we are not able to remove it. But since we are going to have the next generation of our core SDK soon, we will leave it for now and fix this by releasing the new generation.  
The current latest version is v2.35.2.  Please use v2 instead of v3.

**Comment by ubuntudroid** [comment]
@yuhao900914 Can you make sure to to not release a `v3.35.x` version in the future? Because all dependabot users will not be notified about that version if they choose to skip it now.
