### ISSUE TITLE
How to set withUserProperties in LogEvent

### ISSUE THREAD

**Issue by wlxo0401** [amplitude/Amplitude-Android#394]
`Amplitude.instance().logEvent("complete_login_drv", withEventProperties: nil, withUserProperties: withEventProperties)`

The above code is for Amplitude-iOS.

![image_2024_03_07T05_50_47_041Z](https://github.com/amplitude/Amplitude-Android/assets/57979066/77847607-60a7-424e-a1b0-d2f269655e3c)

But I can't see it on Android. How can I use it?

**Comment by izaaz** [comment]
@wlxo0401 - It doesn't look like its supported in this library. You'll need to call `setUserProperties` first so that the user properties are assigned to that user. And then when you track an event, the user properties will get attached to the event that gets fired (this happens within Amplitude backend)

Out of curiosity - is there a reason why you aren't using the new SDK? This functionality is supported in the new SDK. 

This SDK is in maintenance mode.
