### ISSUE TITLE
Still causing app crashes due to failed SQL allocation

### ISSUE THREAD

**Issue by xiphirx** [amplitude/Amplitude-Android#42]
Since it seems like issue #19 is not being looked at, the issue still persists even after updating:

Still exists on v1.6.2,

Device types:
![image](https://cloud.githubusercontent.com/assets/993832/7528014/354dbb96-f4d7-11e4-840f-29e61f967872.png)

Android versions:
![image](https://cloud.githubusercontent.com/assets/993832/7528016/3f519450-f4d7-11e4-9375-778c90af93ed.png)

```
0	android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.
1	at android.database.CursorWindow.<init>(CursorWindow.java:109)
2	at android.database.CursorWindow.<init>(CursorWindow.java:100)
3	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
4	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:301)
5	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
6	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
7	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
8	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
9	at com.amplitude.api.DatabaseHelper.getEvents(DatabaseHelper.java:91)
10	at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:594)
11	at com.amplitude.api.AmplitudeClient.updateServer(AmplitudeClient.java:582)
12	at com.amplitude.api.AmplitudeClient.access$1400(AmplitudeClient.java:31)
13	at com.amplitude.api.AmplitudeClient$4.run(AmplitudeClient.java:343)
14	at android.os.Handler.handleCallback(Handler.java:733)
15	at android.os.Handler.dispatchMessage(Handler.java:95)
16	at android.os.Looper.loop(Looper.java:136)
17	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by curtisliu** [comment]
Yes, we're aware of this and still looking into the issue. Will keep you updated.

**Comment by niqo01** [comment]
@xiphirx just curious, How often this issue occur?

**Comment by benjamin-bader** [comment]
It's one of our top crashes.  We see between 60-200 per day at KeepSafe.

**Comment by curtisliu** [comment]
We're still trying to track down the cause. One possibility is that the device is running low on memory.

**Comment by ngn33r** [comment]
@benjamin-bader - what percentage of unique users per day does that represent?

**Comment by benjamin-bader** [comment]
A small percentage, to be sure - that's out of 1-3 million sessions per day.

**Comment by djih** [comment]
We've spent some extensive time this week investigating this crash. So basically the crash happens when our SDK attempts to read saved events or saved event meta data from our SQLite database. Our SDK creates a cursor object to perform the query, and it crashes when it is unable to allocate that cursor. Many posts and articles online say that there are 2 possible causes for this:

1. The cursor objects are not closed properly after use, causing them to accumulate and your app reaches a point where it is unable to allocate new ones.
http://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed

2. The app itself uses a lot of memory, and there isn't enough free memory to allocate a new cursor object.
https://github.com/greenrobot/greenDAO/issues/154

We do not believe the cause is #1. Our database interactions are pretty simple, and we properly close all of our database objects after use. Here are the 2 places where we use cursors: 
https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/DatabaseHelper.java#L203-L227
https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/DatabaseHelper.java#L239-L266

Additionally, as suggested by http://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed/28155638#28155638, we enabled StrictMode on our Android Demo app in testing, which is supposed to notify us if there is a cursor leak, and there wasn't.

It could be caused by #2. Is it possible that you guys might have a memory leak in your app? Or you guys are also using a SQLite database? You could try running your app in debug mode with StrictMode enabled like in the above post, and see if it reveals any leaks. Something like this:

@Override
public void onCreate(Bundle savedInstanceState) {
    StrictMode.setVmPolicy(
        new StrictMode.VmPolicy.Builder()
            .detectActivityLeaks()
            .detectLeakedClosableObjects()
            .detectLeakedSqlLiteObjects()
            .penaltyLog()
            .penaltyDeath()
            .build()
    );

    super.onCreate(savedInstanceState);
}

The StrictMode builder might also have some other detection flags that you can enable, but we only enabled the ones for detecting leaked database objects.

**Comment by xiphirx** [comment]
So, 1 year out, we're seeing a very low amount of these crashes. For the crashes that are still lingering, it does seem to be due to a low amount of memory. Devices that crashed report ~10-20% of free memory available

I've also noticed an insane number of threads for the devices that are reporting the crashes today, utilizing the name pattern `Thread-*`, which is very odd considering all of our thread pools are named and limited.

Our app is very heavy on its memory use, so I'm not surprised some people would run out of memory and subsequently run into this issue, however the number of users experiencing this issue is so low today that I don't think there is much action to take here.

**Comment by djih** [comment]
@xiphirx that's very interesting. Our Android SDK only spawns 2 background threads, one to handle all DB interactions such as logging events and updating user/deviceid (the "logThread"), and one to upload events (the "httpThread"): https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L169-L176

A lot of our methods call this internal method to schedule tasks on the logThread to maintain chronological ordering: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L1789-L1795

Any idea where those `Thread-*` are coming from? I don't think they're coming from our SDK. I can try running our demo app and using Traceview or DDMS to look at the threads and make sure.

**Comment by xiphirx** [comment]
I don't think they're coming from Amplitude either. It seems like they're coming from the PDF rendering library we use... ugh.

Anyway, it does seem like this is caused due to lack of memory, as the error describes. For our purposes, it is crashing very, very rarely (1 - 3 crashes a day out of millions of sessions), so I wont spend too much effort investigating ways to mitigate it.

**Comment by djih** [comment]
I think it's at least worth investigating on our end if we can handle this gracefully to prevent crashing the app, although OOM crashes are challenging to handle correctly. If it can't fetch the unsent events that's fine it can do it at some other time. The main issue is fetching the existing device id, perhaps the SDK should just not log events until it has a chance to re-initialize with the correct device id.

**Comment by djih** [comment]
@xiphirx I have an initial PR to try and catch / handle CursorWindowAllocationExceptions: https://github.com/amplitude/Amplitude-Android/pull/123. Our SDK queries from the database in 3 specific cases, so we can handle the exception behavior for each of the cases (see the PR comments). I'm also wondering if for some reason this exception is thrown when fetching unsent events and could impact flushing during app close. That might be something we could look into as well.

**Comment by xiphirx** [comment]
Sounds good. I'll be sure to update when a new version is available.

**Comment by djih** [comment]
We added a patch to catch and handle CursorWindowAllocationExceptions in v2.10.0: https://github.com/amplitude/Amplitude-Android/releases/tag/v2.10.0

(@xiphirx we're giving you a separate version that also has diagnostic logging by EOD Friday)
